#!/usr/bin/env sh

# Get the list of staged files
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM)

# Check if any staged files are in ParkingMate.Client
CLIENT_FILES=$(echo "$STAGED_FILES" | grep "^ParkingMate.Client/")

# If there are staged files in ParkingMate.Client, run the linter
if [ -n "$CLIENT_FILES" ]; then
  echo "Running Biome linter on staged files in ParkingMate.Client..."
  cd ParkingMate.Client && pnpm biome:fix && pnpm biome:lint:global && pnpm build
fi
