# .github/workflows/azure-frontend-deploy.yml
name: Deploy Frontend to Azure

on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: parkingmate
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies (npm workspaces)
      run: npm install

    - name: Generate API client types (npm workspace)
      run: npm --workspace @parkingmate/api-client run api:generate

    - name: Build API client package (npm workspace)
      run: npm --workspace @parkingmate/api-client run build

    - name: Build frontend (npm workspace)
      run: npm --workspace @parkingmate/ui run build
      env:
        VITE_API_BASE_URL: https://parkingmate-api-staging.azurewebsites.net/api/v1
        NODE_ENV: production

    - name: Verify build output
      run: |
        echo "Checking build output..."
        if [ ! -d "apps/web/dist" ]; then
          echo "ERROR: apps/web/dist not found!"
          exit 1
        fi
        echo "Build output verified:"
        ls -la apps/web/dist/

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_API_STAGING }}
        package: apps/web/dist