name: Backend Production Deploy 

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/api/**'
      - 'packages/**'
      - 'package.json'
      - 'pnpm-workspace.yaml'
      - 'pnpm-lock.yaml'
      - 'startup.sh'
      - 'web.config'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: parkingmate-api
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: apps/api
        shell: bash
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'pnpm'

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.15.0

    - name: Install dependencies
      run: pnpm install --frozen-lockfile --prefer-offline

    - name: Generate API types
      run: pnpm api:generate

    - name: Build backend API
      run: pnpm build

    - name: Verify build output
      run: |
        if [ ! -d "dist" ]; then
          echo "ERROR: Build output not found in dist/"
          ls -la
          exit 1
        fi
        echo "Build output verified:"
        ls -la dist/

    - name: Prepare deployment files
      run: |
        cd ../..
        # Verify startup script exists and is executable
        if [ ! -f "startup.sh" ]; then
          echo "ERROR: startup.sh not found!"
          exit 1
        fi
        chmod +x startup.sh
        
        # Verify web.config exists
        if [ ! -f "web.config" ]; then
          echo "ERROR: web.config not found!"
          exit 1
        fi
        
        # Create deployment package
        zip -r web-app.zip \
          .deployment \
          startup.sh \
          web.config \
          package.json \
          pnpm-workspace.yaml \
          pnpm-lock.yaml \
          apps/api/dist \
          apps/api/package.json \
          packages/ \
          -x "**/node_modules/*" \
          -x "**/.git/*" \
          -x "**/.github/*" \
          -x "**/.turbo/*" \
          -x "**/*.log" \
          -x "**/test/*" \
          -x "**/*.test.*"

        echo "Deployment package created:"
        unzip -l web-app.zip | head -20

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: web-app.zip