name: Production Deploy 

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: parkingmate-prod
  AZURE_WEBAPP_PACKAGE_PATH: 'dist'
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.15.0

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install --frozen-lockfile --prefer-offline

    - name: Generate API client
      run: |
        pnpm --filter @parkingmate/api api:generate
        pnpm --filter @parkingmate/api-client api:generate

    - name: Build application
      run: pnpm build
      env:
        CI: false

    - name: Prepare deployment files
      run: |
        # Ensure startup script has executable permissions
        chmod +x startup.sh
        
        # Verify build output exists
        echo "Checking build output..."
        if [ ! -d "apps/api/dist" ]; then
          echo "ERROR: apps/api/dist not found!"
          exit 1
        fi
        
        echo "Build output verified:"
        ls -la apps/api/dist/
        
    - name: Zip artifact for deployment
      run: |
        # Create deployment package excluding node_modules (matches Azure rsync logs)
        # Azure will handle node_modules installation via package.json
        zip -r web-app.zip . \
          -x "node_modules/*" \
          -x ".git/*" \
          -x ".github/*" \
          -x ".turbo/*" \
          -x "*.log" \
          -x "apps/*/node_modules/*" \
          -x "packages/*/node_modules/*"
        
        echo "Deployment package created:"
        unzip -l web-app.zip | grep "apps/api/dist" | head -20

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: web-app.zip

    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: ./
        retention-days: 5